//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SubscriptionsApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BranchPolicy
    {
        public System.Guid BranchPolicyID { get; set; }
        public System.Guid BranchID { get; set; }
        public Nullable<System.DateTime> OpeningHour { get; set; }
        public Nullable<System.DateTime> ClosureHour { get; set; }
        public System.DateTime CreationDate { get; set; }
        public System.Guid CreationBy { get; set; }
        public System.DateTime EditDate { get; set; }
        public System.Guid EditedBy { get; set; }
    
        public virtual Branch Branch { get; set; }
    }
}
