//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SubscriptionsApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Party
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Party()
        {
            this.Invoices = new HashSet<Invoice>();
            this.Memberships = new HashSet<Membership>();
            this.Payments = new HashSet<Payment>();
            this.Users = new HashSet<User>();
        }
    
        public System.Guid PartyID { get; set; }
        public string PartyFirstName { get; set; }
        public string PartyLastName { get; set; }
        public System.Guid CompanyBranchId { get; set; }
        public Nullable<System.Guid> PartyTypeId { get; set; }
        public string Email { get; set; }
        public string Telephone { get; set; }
        public string Mobile { get; set; }
        public string Fax { get; set; }
        public string Address { get; set; }
        public Nullable<int> GenderID { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public Nullable<int> KidsNo { get; set; }
        public Nullable<int> MaritalStatus { get; set; }
        public Nullable<System.DateTime> Anniversary { get; set; }
        public Nullable<int> CountryID { get; set; }
        public Nullable<int> CityID { get; set; }
        public string Picture { get; set; }
        public string Note { get; set; }
        public bool IsIndividual { get; set; }
        public string ContactPersonName { get; set; }
        public string ContactPersonEmail { get; set; }
        public string ContactPersonTelephone { get; set; }
        public string CommercialReg { get; set; }
        public string TaxCard { get; set; }
        public Nullable<int> PartyCode { get; set; }
        public System.DateTime EditDate { get; set; }
        public System.Guid EditedBy { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual City City { get; set; }
        public virtual Country Country { get; set; }
        public virtual GenderLookup GenderLookup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoice> Invoices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Membership> Memberships { get; set; }
        public virtual PartiesTypeLookup PartiesTypeLookup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> Users { get; set; }
    }
}
