//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SubscriptionsApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProgramPackage
    {
        public System.Guid PackageID { get; set; }
        public Nullable<System.Guid> ParentProgramId { get; set; }
        public Nullable<System.Guid> ChildProgramId { get; set; }
        public Nullable<decimal> ChildProgramFees { get; set; }
        public Nullable<int> ChildVisitsCount { get; set; }
    
        public virtual Program Program { get; set; }
        public virtual Program Program1 { get; set; }
    }
}
