//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SubscriptionsApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Program
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Program()
        {
            this.Memberships = new HashSet<Membership>();
            this.ProgramConfigurations = new HashSet<ProgramConfiguration>();
            this.ProgramPackages = new HashSet<ProgramPackage>();
            this.ProgramPackages1 = new HashSet<ProgramPackage>();
        }
    
        public System.Guid ProgramID { get; set; }
        public System.Guid DivisionID { get; set; }
        public string ProgramName { get; set; }
        public decimal ProgramFees { get; set; }
        public string ProgramBasis { get; set; }
        public Nullable<int> Length { get; set; }
        public string LengthUnit { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> No_Of_Visists { get; set; }
        public Nullable<int> MaxNo_Of_Members { get; set; }
        public string Description { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.Guid> ClonedFrom { get; set; }
        public System.DateTime CreationDate { get; set; }
        public System.Guid CreationBy { get; set; }
        public System.DateTime EditDate { get; set; }
        public System.Guid EditedBy { get; set; }
    
        public virtual Division Division { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Membership> Memberships { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProgramConfiguration> ProgramConfigurations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProgramPackage> ProgramPackages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProgramPackage> ProgramPackages1 { get; set; }
    }
}
