//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SubscriptionsApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProgramConfiguration
    {
        public System.Guid ProgramID { get; set; }
        public System.Guid BrunchID { get; set; }
        public string ProgramDays { get; set; }
        public Nullable<System.DateTime> ProgramTimeFrom { get; set; }
        public Nullable<System.DateTime> ProgramTimeTo { get; set; }
        public Nullable<int> ProgramCapacity { get; set; }
        public Nullable<int> ValidationDuration { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual Program Program { get; set; }
    }
}
