//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SubscriptionsApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatusCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StatusCategory()
        {
            this.StatusLookups = new HashSet<StatusLookup>();
            this.StatusCategories1 = new HashSet<StatusCategory>();
        }
    
        public System.Guid CategoryID { get; set; }
        public string categoryTitle { get; set; }
        public string description { get; set; }
        public Nullable<System.Guid> ParentID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StatusLookup> StatusLookups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StatusCategory> StatusCategories1 { get; set; }
        public virtual StatusCategory StatusCategory1 { get; set; }
    }
}
