//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SubscriptionsApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Loggings = new HashSet<Logging>();
            this.UserPreferences = new HashSet<UserPreference>();
            this.Roles = new HashSet<Role>();
        }
    
        public System.Guid UserID { get; set; }
        public System.Guid PartyID { get; set; }
        public Nullable<System.Guid> BranchID { get; set; }
        public Nullable<System.Guid> DivisionID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<System.Guid> VerificationToken { get; set; }
        public int FailedPasswordAttemptCount { get; set; }
        public bool IsLocked { get; set; }
        public bool IsAdmin { get; set; }
        public Nullable<bool> IsBlockedByAdmin { get; set; }
        public System.DateTime SubscriptionDate { get; set; }
        public bool MustChangePassword { get; set; }
        public Nullable<System.DateTime> PasswordExpirationDate { get; set; }
        public Nullable<System.DateTime> LastLoginDate { get; set; }
        public bool ShowUserDataOnly { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public System.DateTime EditDate { get; set; }
        public System.Guid EditedBy { get; set; }
    
        public virtual Branch Branch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Logging> Loggings { get; set; }
        public virtual Party Party { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserPreference> UserPreferences { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Role> Roles { get; set; }
    }
}
