//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SubscriptionsApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPreference
    {
        public System.Guid SettingsID { get; set; }
        public System.Guid UserID { get; set; }
        public Nullable<int> LanguageID { get; set; }
        public string DateFormat { get; set; }
        public string TimeFormat { get; set; }
        public Nullable<int> currencyID { get; set; }
        public Nullable<int> AlertDays { get; set; }
        public Nullable<int> AlertVisits { get; set; }
        public Nullable<int> AlertPayments { get; set; }
    
        public virtual Currency Currency { get; set; }
        public virtual Language Language { get; set; }
        public virtual User User { get; set; }
    }
}
